version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pull loadimpact/k6 image.."
      - docker pull loadimpact/k6
  build:
    commands:
      - echo "Test performa curso k6"
      - docker run -i loadimpact/k6 run - < modulo5_conteudo_adicional/aula36_execução_aws_c_git.js -e URL=https://test-api.k6.io/public
  post_build:
    commands:
      - echo "Performance test complete"
