name: K6 load test
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Teste a ser executado'
        required: true
        default: 'modulo5_conteudo_adicional/aula36_execução_aws_c_git.js -e URL=https://test-api.k6.io/public --out json=output.json'
permissions:
  contents: write
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v4

      - name: step 2 - run k6 load test
        uses: grafana/k6-action@v0.2.0
        with: 
          filename: ${{github.event.inputs.command}}

      - name: step 3 - list generated files
        run: ls -al

      - name: step 4 - create report directory
        run: mkdir -p report

      - name: step 5 - move generated files
        run: sudo mv teste_k6.html report/

      - name: step 6 - list files in report directory
        run: ls -al report

      - name: step 7 - upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: test_report
          path: report
      
      - name: step 8 - publish report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report
