name: K6 load test
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Teste a ser executado'
        required: true
        default: 'modulo5_conteudo_adicional/aula36_execução_aws_c_git.js -e URL=https://test-api.k6.io/public'
permissions:
  contents: write
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v3

      - name: step 2 - run k6 load test
        uses: grafana/k6-action@v0.2.0
        with: 
          filename: ${{ github.event.inputs.command }}
          grafana-api-url: https://your-grafana-tempo-url/api # Substitua pelo URL correto do Grafana Tempo
          grafana-api-token: ${{ secrets.GRAFANA_API_TOKEN }}

      - name: step 3 - upload artifact
        uses: actions/upload-artifact@v3
        with: 
          name: relatorio de testes de performance
          path: grafana-report

      - name: step 4 - publish report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: grafana-report
