name: K6 load test
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Teste a ser executado'
        required: true
        default: 'K6_WEB_DASHBOARD=true K6_WEB_DASHBOARD_EXPORT=resultado_test.html k6 run modulo5_conteudo_adicional/aula36_execução_aws_c_git.js -e URL=https://test-api.k6.io/public'
permissions:
  contents: write
jobs:
  build: 
    name: K6 load test
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - checkout
        uses: actions/checkout@v4

      - name: step 2 - install k6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: step 3 - run k6 load test
        run: ${{github.event.inputs.command}}

      - name: step 4 - list generated files
        run: ls -al

      - name: step 5 - create report directory
        run: mkdir -p report

      - name: step 6 - move generated files
        run: mv resultado_test.html report/

      - name: step 7 - list files in report directory
        run: ls -al report

      - name: step 8 - upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: report test performance
          path: report
      
      - name: step 9 - publish report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report
